# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cf9347aa57a0521006316ec58dbb813596ef2650503e5dcc187ef6085b21411fc46e02aae46c67f9a0fa12533ba9341de6cb38af5d63e27ba41454b4aa6c7d3c

test:
  secret_key_base: ab26f4c792513143483be6cef2ea90bbe854ec8a7f72a51277a57344698cd2776697f40a8dc9525cc5ea916a416af85905b2c9016fb8a68999309d1e9670c2c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
